/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./app/**/*.{js,jsx,ts,tsx}', './src/**/*.{js,jsx,ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        'on-tertiary': '#ffffff',
        'surface-dim': '#d9dadb',
        'inverse-surface': '#2e3132',
        'surface-container': '#edeeef',
        surface: '#f8f9fa',
        'on-secondary-fixed': '#002113',
        outline: '#707974',
        'on-secondary-container': '#00714d',
        secondary: '#006c49',
        'secondary-container': '#6cf8bb',
        'surface-variant': '#e1e3e4',
        'on-error-container': '#93000a',
        'surface-tint': '#2b6954',
        'inverse-primary': '#95d3ba',
        'tertiary-fixed-dim': '#ffb95f',
        'on-primary-fixed': '#002117',
        'surface-container-high': '#e7e8e9',
        background: '#f8f9fa',
        'primary-container': '#064e3b',
        'on-surface-variant': '#404944',
        'tertiary-container': '#623c00',
        'surface-container-highest': '#e1e3e4',
        'on-primary': '#ffffff',
        'error-container': '#ffdad6',
        'on-tertiary-container': '#f69f0d',
        'primary-fixed': '#b0f0d6',
        'surface-container-low': '#f3f4f5',
        error: '#ba1a1a',
        'on-primary-fixed-variant': '#0b513d',
        primary: '#003527',
        'tertiary-fixed': '#ffddb8',
        'on-secondary-fixed-variant': '#005236',
        'on-background': '#191c1d',
        'outline-variant': '#bfc9c3',
        'secondary-fixed': '#6ffbbe',
        'on-surface': '#191c1d',
        'surface-bright': '#f8f9fa',
        'on-error': '#ffffff',
        'primary-fixed-dim': '#95d3ba',
        'on-secondary': '#ffffff',
        tertiary: '#442800',
        'on-tertiary-fixed': '#2a1700',
        'on-tertiary-fixed-variant': '#653e00',
        'surface-container-lowest': '#ffffff',
        'on-primary-container': '#80bea6',
        'inverse-on-surface': '#f0f1f2',
        'secondary-fixed-dim': '#4edea3',
        safe: '#10B981',
        'safe-container': '#d1fae5',
        warning: '#F59E0B',
        'warning-container': '#fef3c7',
        danger: '#EF4444',
        'danger-container': '#fee2e2',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'stack-md': '1rem',
        'margin-mobile': '1.5rem',
        'touch-target-min': '3.5rem',
        'gutter-mobile': '1rem',
        'stack-sm': '0.5rem',
        'stack-lg': '2rem',
      },
      fontFamily: {
        'label-lg': ['Atkinson Hyperlegible Next'],
        'body-md': ['Atkinson Hyperlegible Next'],
        'headline-lg': ['Atkinson Hyperlegible Next'],
        'body-lg': ['Atkinson Hyperlegible Next'],
        'headline-md': ['Atkinson Hyperlegible Next'],
        button: ['Atkinson Hyperlegible Next'],
      },
      fontSize: {
        'label-lg': ['16px', { lineHeight: '24px', letterSpacing: '0.01em', fontWeight: '600' }],
        'body-md': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['20px', { lineHeight: '30px', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        button: ['18px', { lineHeight: '24px', fontWeight: '700' }],
      },
    },
  },
};
